### ISSUE TITLE
hello,sir

### ISSUE THREAD

**Issue by xiecuijuan** [larics/larics_motion_planning#2]
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "aerial_manipulators_control" with any of the following names:

    aerial_manipulators_controlConfig.cmake
    aerial_manipulators_control-config.cmake

  Add the installation prefix of "aerial_manipulators_control" to
  CMAKE_PREFIX_PATH or set "aerial_manipulators_control_DIR" to a directory
  containing one of the above files.  If "aerial_manipulators_control"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

when i build this progrem,i meet some problem and the  aerial_manipulators_control is lack.

**Comment by fpetric** [comment]
Hi @xiecuijuan, as we are still working on the development, the package is not self contained and there are several other packages that you need to install. Not sure if you checked the [wiki](https://github.com/larics/larics_motion_planning/wiki/Installation) for installation instructions, it states that you need these packages:
```
Additionally, you will need to install some packages into your workspace:

git clone https://github.com/larics/aerial_manipulators.git

git clone https://github.com/suiauthon/impedance_control

git clone https://github.com/larics/topp_ros.git

git clone https://github.com/larics/larics_gazebo_worlds.git
```
Hopefully, that will resolve the issue.

**Comment by xiecuijuan** [comment]
> Hi @xiecuijuan, as we are still working on the development, the package is not self contained and there are several other packages that you need to install. Not sure if you checked the [wiki](https://github.com/larics/larics_motion_planning/wiki/Installation) for installation instructions, it states that you need these packages:
> 
> ```
> Additionally, you will need to install some packages into your workspace:
> 
> git clone https://github.com/larics/aerial_manipulators.git
> 
> git clone https://github.com/suiauthon/impedance_control
> 
> git clone https://github.com/larics/topp_ros.git
> 
> git clone https://github.com/larics/larics_gazebo_worlds.git
> ```
> 
> Hopefully, that will resolve the issue.

thank you.sir.but i try this way can not slove the problem.ai.i can not find the better way

**Comment by fpetric** [comment]
Can you try checking out devel branch of aerial_manipulators package?

**Comment by xiecuijuan** [comment]
> Can you try checking out devel branch of aerial_manipulators package?

haha,think you.sir.
the way you said solve my trouble.
hahaha.
感谢小哥哥。

**Comment by fpetric** [comment]
Glad we could resolve this.

**Comment by kailash197** [comment]
@fpetric  @xiecuijuan 
I am trying to get simulation running but can't find the imepedance_control repo which is a requirement for aerial_manipulators_control
. Please suggest.
`git clone https://github.com/suiauthon/impedance_control`
